server:
  url: http://localhost:5000
  bind:
    host: 0.0.0.0
    port: 5000
  mimetype: application/json
  encoding: utf-8
  language: en-US
  cors: false # Enable after installing flask-cors
  pretty_print: true
  limit: 100
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: (c) OpenStreetMap contributors
  limits:
    default_items: 100 # what the HTML UI uses by default
    max_items: 10000 # hard cap available in the UI

debug: false

logging:
  level: INFO
  logfile:
  format: "%(asctime)s %(levelname)s %(message)s"

metadata:
  identification:
    title: pi_maker jitter_sin EDR API
    description: EDR endpoint exposing a jitter_sin coverage derived from the Fortran bindings.
    keywords:
      - jitter_sin
      - ogc-edr
      - coverage
    keywords_type: theme
    language: en-US
    url: https://github.com/augustfe/pi_maker
    terms_of_service: https://example.com/terms
  provider:
    name: pi_maker
    url: https://github.com/augustfe/pi_maker
  contact:
    name: August Femtehjell
    position: Software Engineer
    email: someone@example.com
  license:
    name: MIT
    url: https://opensource.org/license/mit

resources:
  jitter-sin-edr:
    type: collection
    title: jitter_sin (EDR coverage)
    description: Sparse spatio-temporal cube marking the daily jitter_sin position.
    keywords:
      - jitter_sin
      - coverage
      - demo
    extents:
      spatial:
        {
          bbox: [-180, -90, 180, 90],
          crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84,
        }
    parameters:
      is_on_path:
        type: parameter
        observedProperty:
          {
            label: Trajectory presence,
            description: "1 if point falls in cell at this time, else 0",
          }
        unit: { label: "1", symbol: "1" }
    links:
      - rel: data
        type: application/prs.coverage+json
        title: "Example: position at lon=10, lat=60 (all times)"
        href: "/collections/jitter-sin-edr/position?coords=POINT(10%2060)&parameter-name=is_on_path"
      - rel: data
        type: application/prs.coverage+json
        title: "Example: position at lon=10, lat=60 (year 2000)"
        href: "/collections/jitter-sin-edr/position?coords=POINT(10%2060)&parameter-name=is_on_path&datetime=2000-01-01/2000-12-31"
    providers:
      - type: edr
        name: pygeoapi.provider.xarray_edr.XarrayEDRProvider
        data: data/jittersin_cube.nc
        x_field: lon
        y_field: lat
        time_field: time
        format: { name: CoverageJSON, mimetype: application/prs.coverage+json }

  jitter-sin-track:
    type: collection
    title: jitter_sin trajectory (preview)
    description: Daily trajectory of the jitter_sin perturbation over one year.
    keywords:
      - jitter_sin
      - trajectory
      - demo
    extents:
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: GeoJSON
        data: data/jittersin_trajectory.geojson
        id_field: name
